package gui;

import javax.swing.*;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import java.awt.*;

/**
 * Created by Arga Ghulam Ahmad on 5/10/2017.
 */

/**
 * Kelas ini merupakan frame pada sesi login user.
 */
public class LoginFrame extends JFrame {
    private JPanel rootPanel;
    private JButton signInButton;
    private JTextField usernameField;
    private JPasswordField passwordField;
    private JLabel usernameLabel;
    private JLabel passwordLabel;
    private JLabel loginLogo;

    public LoginFrame() {
        $$$setupUI$$$();

        setTitle("OwJek - Login");
        ImageIcon icon = new ImageIcon("src/img/Asset 3.png");
        setIconImage(icon.getImage());
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width, screenSize.height);
        setLocationByPlatform(true);
        setExtendedState(Frame.MAXIMIZED_BOTH);
        setLayout(new BorderLayout());

        setContentPane(rootPanel);

        pack();
        setVisible(true);

        signInButton.addActionListener(e -> {
            MainFrame mainframe = new MainFrame(usernameField.getText());
            dispose();
        });
    }

    public static void main(String[] args) {
        LoginFrame loginframe = new LoginFrame();
    }

    /**
     * Inisiasi komponen ui pada frame login.
     */
    private void createUIComponents() {
        usernameField = new JTextField();
        passwordField = new JPasswordField();
        Border roundedBorder = new LineBorder(Color.lightGray, 3, true); // the third parameter - true, says it's round
        usernameField.setBorder(roundedBorder);
        passwordField.setBorder(roundedBorder);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        rootPanel.setBackground(new Color(-16738680));
        rootPanel.setForeground(new Color(-5054501));
        usernameField.setForeground(new Color(-16777216));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 3;
        gbc.gridwidth = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(usernameField, gbc);
        passwordField.setForeground(new Color(-16777216));
        gbc = new GridBagConstraints();
        gbc.gridx = 9;
        gbc.gridy = 5;
        gbc.gridwidth = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(passwordField, gbc);
        signInButton = new JButton();
        signInButton.setBackground(new Color(-16738680));
        signInButton.setFont(new Font("Monospaced", signInButton.getFont().getStyle(), signInButton.getFont().getSize()));
        signInButton.setText("Sign In");
        gbc = new GridBagConstraints();
        gbc.gridx = 16;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(signInButton, gbc);
        final JSeparator separator1 = new JSeparator();
        separator1.setBackground(new Color(-16738680));
        separator1.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 16;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        rootPanel.add(separator1, gbc);
        final JSeparator separator2 = new JSeparator();
        separator2.setBackground(new Color(-16738680));
        separator2.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 16;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        rootPanel.add(separator2, gbc);
        final JSeparator separator3 = new JSeparator();
        separator3.setBackground(new Color(-16738680));
        separator3.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 16;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        rootPanel.add(separator3, gbc);
        usernameLabel = new JLabel();
        usernameLabel.setFont(new Font("Consolas", Font.PLAIN, 20));
        usernameLabel.setText("Username");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        rootPanel.add(usernameLabel, gbc);
        passwordLabel = new JLabel();
        passwordLabel.setFont(new Font("Consolas", Font.PLAIN, 20));
        passwordLabel.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        rootPanel.add(passwordLabel, gbc);
        final JSeparator separator4 = new JSeparator();
        separator4.setBackground(new Color(-16738680));
        separator4.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 0, 0);
        rootPanel.add(separator4, gbc);
        final JSeparator separator5 = new JSeparator();
        separator5.setBackground(new Color(-16738680));
        separator5.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        rootPanel.add(separator5, gbc);
        final JSeparator separator6 = new JSeparator();
        separator6.setBackground(new Color(-16738680));
        separator6.setForeground(new Color(-8336444));
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 10, 0, 0);
        rootPanel.add(separator6, gbc);
        loginLogo = new JLabel();
        loginLogo.setIcon(new ImageIcon(getClass().getResource("/img/Asset 1.png")));
        loginLogo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 17;
        rootPanel.add(loginLogo, gbc);
        final JSeparator separator7 = new JSeparator();
        separator7.setBackground(new Color(-16738680));
        separator7.setForeground(new Color(-16738680));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.gridwidth = 13;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 0, 0, 0);
        rootPanel.add(separator7, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
